FROM ubi8/ubi:latest
MAINTAINER jj <jjserranog@gmail.com>
ENV PORT=8080
LABEL description="A basic Apache container on RHEL 7 UBI"
RUN yum install -y httpd && yum clean all
RUN sed -ri  -e "/Listen 80/c\Listen 0.0.0.0:$PORT" /etc/httpd/conf/httpd.conf &&  chown 48:48 /etc/httpd/logs /run/httpd
COPY ./src/httpd/  /var/www/html/
EXPOSE $PORT
USER apache
ENTRYPOINT ["httpd", "-D", "FOREGROUND"]
